name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2024-08-31
version: '11.0.0-alpha1+508-dev'
project: 'drupal'
datestamp: 1725063560
